/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;

/**
 *
 * @author hp
 */
public class calculator extends javax.swing.JFrame {
    
    double number1, number2;
    char operator;

    /**
     * Creates new form calculator
     */
    public calculator() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        edit_text = new javax.swing.JTextField();
        label_show = new javax.swing.JLabel();
        button_clear = new javax.swing.JButton();
        button_back = new javax.swing.JButton();
        button_sign = new javax.swing.JButton();
        button_division = new javax.swing.JButton();
        button_8 = new javax.swing.JButton();
        button_2 = new javax.swing.JButton();
        button_5 = new javax.swing.JButton();
        button_6 = new javax.swing.JButton();
        button_point = new javax.swing.JButton();
        button_4 = new javax.swing.JButton();
        button_1 = new javax.swing.JButton();
        button_9 = new javax.swing.JButton();
        button_7 = new javax.swing.JButton();
        button_multiplicaion = new javax.swing.JButton();
        button_equal = new javax.swing.JButton();
        button_3 = new javax.swing.JButton();
        button_subtraction = new javax.swing.JButton();
        button_addition = new javax.swing.JButton();
        button_0 = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 204));

        jPanel1.setBackground(new java.awt.Color(50, 50, 50));

        edit_text.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        edit_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_textActionPerformed(evt);
            }
        });

        label_show.setBackground(new java.awt.Color(153, 153, 153));
        label_show.setForeground(new java.awt.Color(153, 153, 153));
        label_show.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        button_clear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        button_clear.setText("c");
        button_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_clearActionPerformed(evt);
            }
        });

        button_back.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        button_back.setText("←");
        button_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_backActionPerformed(evt);
            }
        });

        button_sign.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button_sign.setText("+/-");
        button_sign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_signActionPerformed(evt);
            }
        });

        button_division.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        button_division.setText("÷");
        button_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operator_actions(evt);
            }
        });

        button_8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_8.setText("8");
        button_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbers_action(evt);
            }
        });

        button_2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_2.setText("2");
        button_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbers_action(evt);
            }
        });

        button_5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_5.setText("5");
        button_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbers_action(evt);
            }
        });

        button_6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_6.setText("6");
        button_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbers_action(evt);
            }
        });

        button_point.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        button_point.setText(".");
        button_point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_pointActionPerformed(evt);
            }
        });

        button_4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_4.setText("4");
        button_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbers_action(evt);
            }
        });

        button_1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_1.setText("1");
        button_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbers_action(evt);
            }
        });

        button_9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_9.setText("9");
        button_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbers_action(evt);
            }
        });

        button_7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_7.setText("7");
        button_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbers_action(evt);
            }
        });

        button_multiplicaion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_multiplicaion.setText("×");
        button_multiplicaion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operator_actions(evt);
            }
        });

        button_equal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        button_equal.setText("=");
        button_equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_equalActionPerformed(evt);
            }
        });

        button_3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_3.setText("3");
        button_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbers_action(evt);
            }
        });

        button_subtraction.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_subtraction.setText("-");
        button_subtraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operator_actions(evt);
            }
        });

        button_addition.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_addition.setText("+");
        button_addition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operator_actions(evt);
            }
        });

        button_0.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_0.setText("0");
        button_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbers_action(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(button_subtraction, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(button_4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(button_5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(button_6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(button_addition, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(edit_text)
                        .addComponent(label_show, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(button_sign, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(button_7, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(button_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button_8, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                            .addGap(12, 12, 12)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(button_9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(button_multiplicaion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(button_back, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(button_division, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(button_0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_point, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_equal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(label_show, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edit_text, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(button_division, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button_back))
                            .addComponent(button_sign, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(button_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_multiplicaion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_addition, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_subtraction, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_point, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_equal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_0, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_signActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_signActionPerformed
        // TODO add your handling code here:
        
        edit_text.setText((-1 * Double.parseDouble( edit_text.getText()))+"");
    }//GEN-LAST:event_button_signActionPerformed

    private void button_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_clearActionPerformed
        // TODO add your handling code here:
        
        edit_text.setText("");
        label_show.setText("");
        
    }//GEN-LAST:event_button_clearActionPerformed

    private void button_pointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_pointActionPerformed
        // TODO add your handling code here:

        if (!edit_text.getText().contains(".")) {
            edit_text.setText(edit_text.getText() + ".");
        }

    }//GEN-LAST:event_button_pointActionPerformed

    private void button_equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_equalActionPerformed
        // TODO add your handling code here:
        if (operator != '\u0000') {
            if (edit_text.getText().length() > 0) {
                number2 = Double.parseDouble(edit_text.getText());
            } else {
                number2 = number1;
            }
            
            double result;
            
            switch (operator) {
                
                case '+':
                    result = number1 + number2;
                    edit_text.setText("" + result);
                    // edit_text.setText(String.valueOf(result));
                    label_show.setText(label_show.getText() + number2 + "=");
                    break;
                
                case '/':
                    result = number1 / number2;
                    edit_text.setText("" + result);
                    // edit_text.setText(String.valueOf(result));
                    label_show.setText(label_show.getText() + number2 + "=");
                    break;
                
                case '-':
                    result = number1 - number2;
                    edit_text.setText("" + result);
                    // edit_text.setText(String.valueOf(result));
                    label_show.setText(label_show.getText() + number2 + "=");
                    break;
                
                case '*':
                    result = number1 * number2;
                    edit_text.setText("" + result);
                    // edit_text.setText(String.valueOf(result));
                    label_show.setText(label_show.getText() + number2 + "=");
                    break;
                
            }
            operator = '\u0000';
        } else {
            edit_text.setText(number2 + "");
        }

    }//GEN-LAST:event_button_equalActionPerformed

    private void numbers_action(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbers_action
        // TODO add your handling code here:

        switch (evt.getActionCommand()) {
            
            case "0":
                if (edit_text.getText().length() > 0) {
                    edit_text.setText(edit_text.getText() + "0");
                }
                break;
            
            case "1":
                edit_text.setText(edit_text.getText() + "1");
                break;
            
            case "2":
                edit_text.setText(edit_text.getText() + "2");
                break;
            
            case "3":
                edit_text.setText(edit_text.getText() + "3");
                break;
            
            case "4":
                edit_text.setText(edit_text.getText() + "4");
                break;
            
            case "5":
                edit_text.setText(edit_text.getText() + "5");
                break;
            
            case "6":
                edit_text.setText(edit_text.getText() + "6");
                break;
            
            case "7":
                edit_text.setText(edit_text.getText() + "7");
                break;
            
            case "8":
                edit_text.setText(edit_text.getText() + "8");
                break;
            
            case "9":
                edit_text.setText(edit_text.getText() + "9");
                break;
            
        }

    }//GEN-LAST:event_numbers_action

    private void operator_actions(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operator_actions
        // TODO add your handling code here:
        if (edit_text.getText().length() > 0) {
            
            switch (evt.getActionCommand()) {
                
                case "+":
                    number1 = Double.parseDouble(edit_text.getText());
                    operator = '+';
                    label_show.setText(number1 + "+");
                    edit_text.setText("");
                    break;
                
                case "×":
                    number1 = Double.parseDouble(edit_text.getText());
                    operator = '*';
                    label_show.setText(number1 + "×");
                    edit_text.setText("");
                    break;
                
                case "÷":
                    number1 = Double.parseDouble(edit_text.getText());
                    operator = '/';
                    label_show.setText(number1 + "÷");
                    edit_text.setText("");
                    break;
                
                case "-":
                    number1 = Double.parseDouble(edit_text.getText());
                    operator = '-';
                    label_show.setText(number1 + "-");
                    edit_text.setText("");
                    break;
            }
        }

    }//GEN-LAST:event_operator_actions

    private void edit_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_textActionPerformed

    private void button_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_backActionPerformed
        // TODO add your handling code here:

        if (edit_text.getText().length() > 0) {
            String numbers = edit_text.getText().substring(0, edit_text.getText().length() - 1);
            edit_text.setText(numbers);
            
        }
    }//GEN-LAST:event_button_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_0;
    private javax.swing.JButton button_1;
    private javax.swing.JButton button_2;
    private javax.swing.JButton button_3;
    private javax.swing.JButton button_4;
    private javax.swing.JButton button_5;
    private javax.swing.JButton button_6;
    private javax.swing.JButton button_7;
    private javax.swing.JButton button_8;
    private javax.swing.JButton button_9;
    private javax.swing.JButton button_addition;
    private javax.swing.JButton button_back;
    private javax.swing.JButton button_clear;
    private javax.swing.JButton button_division;
    private javax.swing.JButton button_equal;
    private javax.swing.JButton button_multiplicaion;
    private javax.swing.JButton button_point;
    private javax.swing.JButton button_sign;
    private javax.swing.JButton button_subtraction;
    private javax.swing.JTextField edit_text;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel label_show;
    // End of variables declaration//GEN-END:variables
}
